---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: hello-world
  namespace: flux-system
spec:
  image: harbor.s.wish.site/wish/hello-world
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hello-world
  filterTags:
    pattern: 'dev'
...
